@startuml

class Nave {
    -escudo: Escudo
    -vida: Vida
    -posicion: Posicion
    -movimiento: Movimiento
    -direcciones: Direccion
    -velocidades: Velocidad
    -combustible: Combustible
    -proyectiles: Proyectil
    +mover()
    +disparar()
}
class Menu
class Jugador
class JuegoAsteroids {
    -niveles: Nivel
    -menu: Menu
    -puntaje: Puntaje
    -fondo: Fondo
    -tiempo: Tiempo
    -sonidos: Sonido
    -musica: Musica
    -jugador: Jugador
    -control: Control
    +iniciarJuego()
    +terminarJuego()
}
class Imagen
class Jugador {
    -nave: Nave
    -control: Control
    +actualizarEstado()
}

class Control {
    -nave: Nave
}

class Nivel {
    -estrellas: Estrella
    -planetas: Planeta
}

class PowerUp {
    -tipo
    -duracion
}

class Escudo {
    -energia
}

class Vida {
    -cantidad
}

class Combustible {
    -nivelActual
    -nivelMaximo
}

class Proyectil {
    -posicion: Posicion
    -movimiento: Movimiento
}

class Enemigo {
    +atacar()
}

class NaveEnemiga {
    -posicion: Posicion
    -movimiento: Movimiento
    -disparos: DisparoEnemigo
    +atacar()
}

class DisparoEnemigo {
    -posicion: Posicion
    -movimiento: Movimiento
}

class Asteroide {
    -posicion: Posicion
    -movimiento: Movimiento
}

class Colision {
    +detectarColisiones()
}

class Explosion {
    -particulas: Particula
}

class Puntaje {
    -total: int
}

class Menu {
    +mostrar()
    +ocultar()
}

class Fondo {
    -imagen: Imagen
}

class Imagen {
    -ruta
}

class Tiempo {
    -tiempoRestante
}

class Sonido {
    -archivo
}

class Musica {
    -sonidos
}

class Movimiento {
    -aceleracion
    -rotacion
}

class Posicion {
    -x
    -y
}

class Direccion {
    -angulo
}

class Velocidad {
    -valor
}

class Particula
class Estrella
class Planeta

JuegoAsteroids "1"*--"*" Nivel
JuegoAsteroids *-- Menu
JuegoAsteroids *-- Puntaje
JuegoAsteroids *-- Fondo
JuegoAsteroids*--Tiempo
JuegoAsteroids "1"*--"*" Sonido
JuegoAsteroids*-- Musica
JuegoAsteroids*--Jugador
Jugador*--Nave
Jugador o--Control
JuegoAsteroids"1"*--"*" PowerUp
JuegoAsteroids*--Control
Nave*-- Escudo
Nave*--Vida
Nave*--Posicion
Nave*--Movimiento
Nave"1" o--"*" Direccion
Nave"1" o--"1,2" Velocidad
Nave o-- Combustible
Nave"1" o--"*" Proyectil
Nave"1"*--"*"PowerUp
JuegoAsteroids"1" *-- "*" Enemigo
Enemigo--|>NaveEnemiga
NaveEnemiga*--Posicion
NaveEnemiga*--Movimiento
NaveEnemiga"1" o--"*"DisparoEnemigo
JuegoAsteroids"1"*--"*"Asteroide
Asteroide*--Posicion
Asteroide*--Movimiento
Colision"*" o--"*" Proyectil
Colision"*" o--"*" Asteroide
Colision"*" o--"*" Nave
Colision"*" o--"*" NaveEnemiga
Colision"*"*--"*" Explosion
Explosion"*"*--"*" Particula
Nivel"1"*--"*" Estrella
Nivel"1"*--"*" Planeta
Fondo*--Imagen
Musica"1" o-- "*"Sonido

@enduml